#!/bin/bash

# Compress the dpkg.log file
gzip /var/log/dpkg.log

# Zip the compressed dpkg.log file
zip /var/log/dpkg.log.gz.zip /var/log/dpkg.log.gz

# Read Me Notes 
# In Linux, logs generated by the system are typically stored in the /var/log directory. This directory contains log files for various system components, such as the system itself, the kernel, the boot process, system services, and applications. The log files in the /var/log directory can be rotated, compressed, and rotated on a regular basis to conserve disk space and keep the logs manageable. 
# The exact naming convention and management of log files can vary depending on the distribution and the specific components generating the logs.